flask/app/blueprints/project/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import ValidationError, DataRequired, Length
from wtforms import StringField, TextAreaField, SubmitField, MultipleFileField, SelectField, RadioField, BooleanField


class UploadForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    pdfs = MultipleFileField("PDF Files")
    submit = SubmitField("Submit")

    def validate_pdf_files(self, field):
        for data in field.data:
            if not data.filename.endswith(".pdf"):
                raise ValidationError("Only PDFs are allowed.")


class ReportForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=1, max=256)])
    body = TextAreaField("Body", validators=[DataRequired(), Length(min=1, max=4096)])
    report = SelectField("Report",validators=[DataRequired()])
    status = RadioField("Status", choices=[("Requires changes","Requires changes"),("Approved", "Approved"), ("Not Approved", "Not Approved")], default="Need Changes",validators=[DataRequired()])
    pdf = MultipleFileField("PDF Files")
    submit = SubmitField("Confirm", render_kw={"class": "btn btn-primary"})

    def validate_pdf_files(self, field):
        for data in field.data:
            if not data.filename.endswith(".pdf"):
                raise ValidationError("Only PDFs are  allowed.")
            

class AddCommentForm(FlaskForm):
    body = StringField("Title", validators=[DataRequired(), Length(min=1, max=256)])
    submit = SubmitField("Confirm", render_kw={"class": "btn btn-primary"})
    is_anonymous = BooleanField("Anonymous Comment")  

flask/app/blueprints/project/__init__.py
from flask import Blueprint

bp = Blueprint("project", __name__)

from app.blueprints.project import routes

flask/app/blueprints/project/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from app import db
from app.blueprints.project import bp
from app.blueprints.project.forms import UploadForm, ReportForm, AddCommentForm
from app.models import Project, Draft, Version, Report, ReportDraft, Reviewer, Comment, ReportComment
from app.modules.pdf_helper import upload_pdf, get_all_pdfs, delete_pdf, download_pdf
from sqlalchemy import desc

@bp.route("/projects")
@login_required
def projects():
    if current_user.is_authenticated:

        if current_user.type == "reviewer":
            projects = Project.query.all()
            versions = [p.versions[-1] for p in projects if p.researcher.department == current_user.department]
            return render_template(
                "projects.html", title="All Projects", projects=versions
            )
        else:
            versions = [p.versions[-1] for p in current_user.projects ]
            return render_template(
                "projects.html", title="Your Projects", projects=versions
            )
    else:
        return redirect(url_for("auth.login"))


@bp.route("/reports")
@login_required
def reports():
    reports = Report.query.filter_by(rvid=current_user.uid).all()
    return render_template("reports.html", title="Your Reports", reports=reports)


@bp.route("/project/<int:pid>/version/<int:vid>/add_report/")
@login_required
def add_report(pid, vid):
    form = ReportForm()
    draft = ReportDraft.query.filter_by(pid=pid,rvid= current_user.uid).order_by(desc(ReportDraft.rdid)).first()
    reports = Report.query.filter_by(pid=pid).all()
    if draft and draft.reference != 0:
        report = Report.query.filter_by(rid=draft.reference).first()
        if report:
            form.report.choices = [(draft.reference,str(report.rid)+"-"+str(report.title))]+[(0,"Nothing")]+[(r.rid,str(r.rid) +"-"+str(r.title )) for r in reports if not r.rid == draft.reference]
        else:
            form.report.choices = [(0,"Select a Report to refer")]+[(r.rid,str(r.rid) +"-"+str(r.title )) for r in reports]
    else:
        form.report.choices = [(0,"Select a Report to refer")]+[(r.rid,str(r.rid) +"-"+str(r.title )) for r in reports]
    if not draft:
        new_draft = ReportDraft(
            title = "Title",
            body = "Body",
            rvid = current_user.uid,
            pid = pid,
            status = "Requires changes",
        )
        pdfs = Version.query.filter_by(vid=vid).order_by(Version.created_at.desc()).first_or_404().contains
        new_draft.contains = [pdf for pdf in pdfs]
        db.session.add(new_draft)
        db.session.commit()
        form.title.data = new_draft.title
        form.body.data = new_draft.body
        form.status.data = new_draft.status
    else:
        form.title.data = draft.title
        form.body.data = draft.body
        form.status.data = draft.status
        pdfs = [pdf for pdf in draft.contains]
    pdfs = get_all_pdfs(pdfs)
    return render_template(
        "edit_report.html", title="Add Report",
        counter=len(pdfs),
        form=form,
        pid=pid,
        vid=vid,
        pdfs=pdfs,
    )


@bp.route("/project/create", methods=["GET", "POST"])
@login_required  # this decorator will make sure that the user is logged in
def create():
    form = UploadForm()
    if form.validate_on_submit():
        pdfs = upload_pdf("uploads", form.pdfs.data)
        new_project = Project(researcher=current_user)
        db.session.add(new_project)
        new_project.researcher = current_user
        db.session.commit()

        new_draft = Draft(
            title=form.title.data,
            description=form.description.data,
        )
        new_version = Version(
            version_number=1,
            project_title=form.title.data,
            project_description=form.description.data,
            project_status="Submitted",
            created_at=datetime.now(),
            updated_at=datetime.now(),
            project=new_project,
            draft=new_draft,
        )

        new_draft.version = new_version

        db.session.add(new_version, new_draft)

        # Add the PDF objects to the draft and version
        new_draft.contains = pdfs
        new_version.contains = pdfs

        db.session.commit()

        flash("Congratulations, you have submitted a PDF!")
        return redirect(url_for("main.index"))

    return render_template(
        "projects_components/create_project.html", title="Upload", form=form
    )


@bp.route("/project/view/<int:pid>/<int:version_number>", methods=["GET", "POST"])
@login_required
def view(pid, version_number):
    form = AddCommentForm()
    project = Project.query.filter_by(pid=pid).first_or_404()
    comments = Comment.query.filter_by(pid=pid)
    version  = Version.query.filter_by(pid=pid,version_number=version_number).first_or_404()
    reports = Report.query.filter_by(pid=pid).all()
    if version.version_number > len(project.versions):
        return render_template("errors/404.html"), 404

    get_pdf_lambda = lambda x: get_all_pdfs(x)

    if form.validate_on_submit():
        new_comment = Comment(
            body=form.body.data,
            created_at=datetime.now(),
            uid = current_user.uid,
            pid = pid,
            version_ref = version.version_number,
            anonymous = form.is_anonymous.data
        )

        db.session.add(new_comment)

        db.session.commit()
        return redirect(url_for("project.view", pid=pid, version_number=version.version_number))

    return render_template(
        "view.html",
        title="View Project",
        project=project,
        version_number=version.version_number,
        get_pdf_lambda=get_pdf_lambda,
        form = form,
        comments = comments,
        reports = reports,
    )


@bp.route("/project/edit/<int:vid>")
@login_required
def edit(vid):
    form = UploadForm()
    form_pdf = UploadForm()

    draft = Version.query.filter_by(vid=vid).first_or_404().draft

    form.title.data = draft.title
    form.description.data = draft.description

    pdfs = get_all_pdfs(draft.contains)

    return render_template(
        "projects_components/edit_project.html",
        title="View Project",
        counter=len(pdfs),
        pdfs=pdfs,
        form=form,
        form_pdf=form_pdf,
        vid=vid,
    )


@bp.route("/project/edit_draft/<int:vid>", methods=["POST"])
@login_required
def edit_draft(vid):
    if request.method == "POST":
        draft = Version.query.filter_by(vid=vid).first_or_404().draft

        draft.title = request.form.get("title")
        draft.description = request.form.get("description")
        names = request.form.getlist("names")

        pdfs = upload_pdf("uploads", request.files.getlist("files"))
        draft.contains = [pdf for pdf in draft.contains if pdf.filename in names] + pdfs

        db.session.commit()
        pdfs = draft.contains
        delete_pdf(pdfs)
        return ("", 204)


@bp.route("/project/update_version/<int:vid>", methods=["POST"])
@login_required
def update_version(vid):
    if request.method == "POST":
        version = Version.query.filter_by(vid=vid).first_or_404()
        draft = version.draft
        project = version.project

        new_draft = Draft(
            title=draft.title,
            description=draft.description,
            contains=[pdf for pdf in draft.contains],
        )

        new_version = Version(
            version_number=version.version_number + 1,
            project_title=draft.title,
            project_description=draft.description,
            project_status=version.project_status,
            created_at=datetime.now(),
            updated_at=datetime.now(),
            project=project,
            draft=new_draft,
        )

        new_draft.version = new_version

        db.session.add(new_version, new_draft)
        db.session.commit()

        new_version.contains = [pdf for pdf in new_draft.contains]

        db.session.commit()
        return ("", 204)


@bp.route("/project/discard_draft/<int:vid>", methods=["POST"])
@login_required
def discard_draft(vid):
    if request.method == "POST":
        version = Version.query.filter_by(vid=vid).first_or_404()
        draft = version.draft

        draft.title = version.project_title
        draft.description = version.project_description

        draft.contains = [pdf for pdf in version.contains]

        db.session.commit()
        return ("", 204)

#############################################################################


@bp.route("/project/edit/<int:vid>/edit_pdf/<filename>", methods=["POST", "GET"])
@login_required
def edit_pdf(vid, filename):
    draft = Version.query.filter_by(vid=vid).first_or_404().draft
    name = filename + ".pdf"
    if request.method == "POST":
        pdfs = draft.contains
        delete_pdf(pdfs)
        pdf = request.files["pdf"]
        pdf_obj = upload_pdf("uploads", [pdf])
        draft.contains = [
            pdf for pdf in draft.contains if pdf.filename != name
        ] + pdf_obj
        db.session.commit()
        return ("", 204)

    if request.method == "GET":
        link = download_pdf(name)
        return render_template(
            "edit_pdf.html",
            title="PDF VIEW",
            vid=vid,
            link=link,
            filename=name,
            pid = -1
        )

@bp.route("/project/<int:pid>/edit_report_draft/<int:vid>", methods=["POST"])
@login_required
def edit_report_draft(pid,vid):
    if request.method == "POST":
        draft = ReportDraft.query.filter_by(pid=pid,rvid=current_user.uid).order_by(desc(ReportDraft.rdid)).first_or_404()
        draft.title = request.form.get("title")
        draft.body = request.form.get("body")
        draft.status = request.form.get("status")
        if request.form.get("rport") != None:
            draft.reference = request.form.get("report")
        else:

flask/app/templates/__init__.py
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from app.modules.firebase import Firebase
from flask_bootstrap import Bootstrap
from sqlalchemy import text

login = LoginManager()
login.login_view = "auth.login"

toolbar = DebugToolbarExtension()

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
firebase = Firebase()


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "bucami"
    app.config["ALLOWED_EXTENSIONS"] = ["pdf"]
    app.config[
        "SQLALCHEMY_DATABASE_URI"
    ] = "postgresql://moonphase:eclipse@db:5432/paper_review"
    app.debug = True

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)
    toolbar.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.project import bp as project_bp
    app.register_blueprint(project_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix="/auth")

    return app


from app import models

flask/app/templates/_navbar.html
<nav class="navbar navbar-light navbar-expand-md fixed-top navbar-shrink py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="{{ url_for('main.index') }}">
            <span>Project0</span>
        </a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1">
            <span class="visually-hidden">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item"><a class="nav-link active" href="{{ url_for('main.index') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link active" href="{{ url_for('main.about') }}">About</a></li>
            </ul>
            {% if current_user.is_anonymous %}
            <a class="btn btn-primary shadow" role="button" href="{{ url_for('auth.login') }}">Login</a>
            <a class="ms-2 btn btn-danger shadow" role="button" href="{{ url_for('auth.register') }}">Register</a>
            {% else %}
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    {{ current_user.researcher_fullname() }}
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="{{ url_for('auth.profile', username=current_user.researcher_username() ) }}">Profile</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('auth.edit_profile', username=current_user.researcher_username() ) }}">Edit Profile</a></li>
                    <li><a class="dropdown-item text-danger" href="{{ url_for('auth.logout') }}">Logout</a></li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
</nav>

flask/app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<section class="py-4 py-md-5 my-5">
    <div class="container py-md-5">
        <div class="row">
            <div class="container">
                <div class="main-body">
                  {% include 'about_components/_dev_card.html' %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

flask/app/templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="App" />
        <meta name="keywords" content="App" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">

        {% block styles %}
        {% endblock %}


        {% if title %}
        <title>{{ title }} - Paper Review</title>
        {% else %}
        <title>Paper Review</title>
        {% endif %}
    </head>

    <body>
        {% include 'shared_components/_navbar.html' %}

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}

        {% include 'shared_components/_footer.html' %}

        <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/startup-modern.js') }}"></script>

        {% block scripts %}
        {% endblock %}
    </body>

</html>

flask/app/templates/edit_pdf.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="description" content="App" />
    <meta name="keywords" content="App" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
    <div id="embeddedView"></div>
    <div id="getFile">
        <div id="getFileText"></div>
    </div>

    <script src="https://documentcloud.adobe.com/view-sdk/main.js"></script>
    <script type="text/javascript">
        const urlToPDF = "{{ link }}";
        const pdfFilename = urlToPDF.split("/").slice(-1)[0];

        const clientId = "7b3fa4b76de4458ea63535ac28f82dde";
        const viewerOptions = {
            embedMode: "FULL_WINDOW",
            defaultViewMode: "FIT_PAGE",
            showDownloadPDF: true,
            showPrintPDF: false,
            showLeftHandPanel: false,
            showAnnotationTools: true
        };

        const saveOptions = {
            enableFocusPolling: false,
            showSaveButton: true
        };

        const fetchPDF = async (urlToPDF) => {
            const response = await fetch(urlToPDF);
            const blob = await response.blob();
            return await blob.arrayBuffer();
        };

        const hideLink = () => {
            document.getElementById("getFile").style.display = "none";
        };

        const updateSaveUI = (fileName) => {
            const getFileText = document.getElementById("getFileText");
            const originalFilename = pdfFilename.split("-").slice(0, -1).join("-"); // Extract the original filename
            const timestamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z/, ""); // Generate the timestamp
            const newFilename = `${originalFilename}-${timestamp}.pdf`; // Combine the original filename and timestamp
            getFileText.innerHTML = `You can retrieve your saved file (${newFilename}) from: <a onclick="hideLink(); return true;" href="${fileName}">here.</a>`;
            document.getElementById("getFile").style.display = "flex";
        };

        document.addEventListener("adobe_dc_view_sdk.ready", async () => {
            const adobeDCView = new AdobeDC.View({
                clientId: clientId,
                divId: "embeddedView"
            });

            adobeDCView.registerCallback(
                AdobeDC.View.Enum.CallbackType.SAVE_API,
                async (metaData, content, options) => {
                    const originalFilename = pdfFilename.slice(0, -24);

                    const file = new File([content], originalFilename, { type: 'application/pdf' }); // Create a File object with the original filename
                    console.log(originalFilename);
                    const formData = new FormData();
                    formData.append('pdf', file); // Append the file to the FormData
                    {% if pid == -1 %}
                        const response = await fetch("{{ url_for('project.edit_pdf', vid=vid, filename=filename) }}", {
                    {% else %}
                        const response = await fetch("{{ url_for('project.edit_report_pdf', vid=vid,filename=filename,pid=pid) }}", {
                    {% endif %}
                        method: 'POST',
                        body: formData,
                    });

                    if (response.status === 204) {
                        const text = await response.text();
                        updateSaveUI(text);
                    }

                    return Promise.resolve({
                        code: AdobeDC.View.Enum.ApiResponseCode.SUCCESS,
                        data: {
                            metaData: { fileName: pdfFilename } // Use the original fileName as the metadata
                        }
                    });
                },
                saveOptions
            );

            const previewFilePromise = adobeDCView.previewFile({
                content: { promise: fetchPDF(urlToPDF) },
                metaData: { fileName: pdfFilename }
            }, viewerOptions);
        });

        (function () {
            if (Blob.prototype.arrayBuffer !== "function") {
                Blob.prototype.arrayBuffer = function () {
                    return new Promise((resolve) => {
                        const fileReader = new FileReader();
                        fileReader.onload = () => {
                            resolve(fileReader.result);
                        };
                        fileReader.readAsArrayBuffer(this);
                    });
                };
            }
        })();
    </script>
    </body>

    </html>

flask/app/templates/explaination.html
{% extends "base.html" %}

{% block content %}
<section class="py-4 py-md-5 my-5">
  <div class="container py-md-5">
    <h2 class="text-center mb-4">Welcome to Paper Review</h2>
    <div class="row">

      <!-- Researcher Card -->
      <div class="col-md-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">For Researchers</h5>
            <p class="card-text">Publish your scientific papers and manage their progression over time with an intuitive versioning system. Track changes, update your work, and showcase your scientific journey.</p>
          </div>
        </div>
      </div>

      <!-- Reviewer Card -->
      <div class="col-md-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">For Reviewers</h5>
            <p class="card-text">View different versions of publications, offer your expertise, and create detailed reports. Actively contribute to the refinement and validation of papers, ensuring research meets the highest standards.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

flask/app/templates/footer.html
<footer>
    <div class="container py-4 py-lg-5">
        <div class="row row-cols-2 row-cols-md-4">
            <div class="col-12 col-md-3">
                <div class="fw-bold d-flex align-items-center mb-2"><span>Project0</span></div>
                <p class="text-muted">Sem eleifend donec molestie, integer quisque orci aliquam.</p>
            </div>
            <div class="col-sm-4 col-md-3 text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">Services</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Web design</a></li>
                    <li><a href="#">Development</a></li>
                    <li><a href="#">Hosting</a></li>
                </ul>
            </div>
            <div class="col-sm-4 col-md-3 text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">About</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Company</a></li>
                    <li><a href="#">Team</a></li>
                    <li><a href="#">Legacy</a></li>
                </ul>
            </div>
            <div class="col-sm-4 col-md-3 text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">Careers</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Job openings</a></li>
                    <li><a href="#">Employee success</a></li>
                    <li><a href="#">Benefits</a></li>
                </ul>
            </div>
        </div>
        <hr>
        <div class="text-muted d-flex justify-content-between align-items-center pt-3">
            <p class="mb-0">Copyright © 2023</p>
            <a class="fw-bold" href="https://github.com/MacPapo">MacPapo</a>
            <a class="fw-bold" href="https://github.com/CippoX">CippoX</a>
            <a class="fw-bold" href="https://github.com/MrZhouDawei">MrZhouDawei</a>
            <ul class="list-inline mb-0">
                <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                        fill="currentColor" viewBox="0 0 16 16" class="bi bi-facebook">
                        <path
                            d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z">
                        </path>
                    </svg></li>
                <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                        fill="currentColor" viewBox="0 0 16 16" class="bi bi-twitter">
                        <path
                            d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z">
                        </path>
                    </svg></li>
                <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                        fill="currentColor" viewBox="0 0 16 16" class="bi bi-instagram">
                        <path
                            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z">
                        </path>
                    </svg></li>
            </ul>
        </div>
    </div>
</footer>

flask/app/templates/reports.html
{% extends "base.html" %}
{% from "projects_components/_report_accordion.html" import render_accordions_report %}


{% block content %}

<section class="py-4 py-md-5 my-5">
    <div class="container py-md-5">
        <div class="row">
            {% if not reports %}
                <div class="col-12">
                    <div class="alert alert-info" role="alert">
                        <h4 class="alert-heading">No Reports yet!</h4>
                        <p>You don't have any reports yet. Go to review one by clicking this button below .</p>
                        <hr>
                        <a href="{{ url_for('project.projects') }}" class="btn btn-primary">Check Projects</a>
                    </div>
                </div>
                {% else %}
                <div class="col-12">
                    <h2 class="mb-4">Reports</h2>
                    {{ render_accordions_report(reports) }}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}